### ISSUE TITLE
/cancel for /lwc admin cleanup process

### ISSUE THREAD

**Issue by kennethlinzj** [Tsuser1/Modern-LWC#14] opened 2018-08-26 03:12 UTC
**LWC Version (/lwc admin version): 1.9.4** 
**Server version (/version): "CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)"** 

**Short five word summary of issue:**
 /cancel to stop cleanup process

**Detailed description of problem:**
Requesting /cancel to stop the /lwc admin cleanup process. I find that the process never finishes on its own (it suddenly stops displaying logs without completing) and leaves many tiles loaded in the server, which a restart does not resolve. 

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment] 2018-08-31 02:28
I do not believe this functionality will be necessary with the latest development build(s). We have fixed a lot of the performance issues in saving protections, and so it is many times quicker now. If you have tested your database on the latest development build and you are still not content with the performance, please make another issue and describe your use case in more detail (database type, size, etc).

**Comment by kennethlinzj** [comment] 2018-08-31 08:49
The issue wasn't about quickness, but the fact that it hangs. Restarting it causes it to hang at the same place. This thread was requested to be started by Tsuser1, I am merely helping to post it here.

**Comment by pop4959** [comment] 2018-08-31 09:16
Sorry, I did not mean to be rude. I simply closed this issue since I have not been able to reproduce your issue on the latest development build. So, in other words, it appears to be working. That is why I request additional information if you would like me to inspect the issue further, and perhaps warrant re-opening it.

Perhaps start with the following:

- Have you tested '/lwc admin cleanup' on the latest development build, downloadable from the spigot resource page?
- What database type (SQLite or MySQL)?
- How many protections are there in your database?
- Do you use entity locking?
- Any further information about your set-up or use case.
- Provide your configuration files for LWC if possible.

Please understand that the devil is in the details. Sometimes these kinds of bugs happen for some people and not for others. It might have to do with your specific configuration. If it isn't broken on my test server, there is nothing for me to fix. The command runs in about 5 seconds for me with almost 100,000 protections.

**Comment by kennethlinzj** [comment] 2018-08-31 09:29
Hi, no hard feelings, I'm just restating a few facts in case it was forgotten after a while. 

==

I've not tested the command on the latest development build, because I'm on the older version and am still waiting for the fix that allows us to safely migrate to the newer one. (Any ETA on that one, btw? Just wondering)

SQLite

81,916 protections

Yes, I use entity locking. 

Sue, check the bottom of the post for my core.yml config file.

==

Yup I agree with you that these kinds of bugs are very pesky because it happens for some but not others. However, that's why a cancel command would be incredibly useful for those who do need it. 

I'm not trying to intrude on the development process; please continue doing great work, and thanks for that, I'm just stating my point of view to clear things up, in case of any misunderstanding. If it's too much work to implement the cancel command I'll understand. 

Thanks again. 

**core.yml**

`core:
    locale: en
    flushInterval: 10
    cacheSize: 150000
    precache: -1
    showNotices: true
    showMyNotices: false
    opIsLWCAdmin: true
    disableHistory: false
    townyBorders: false
    groupPrefix: group.
    updateNotifier: false
optional:
    onlyProtectWhenOwnerIsOnline: false
    onlyProtectWhenOwnerIsOffline: false
    exemptBlocks: []
    optOut: false
    blacklistedBlocks:
    - '166'
    - '154'
    blacklistedPlayers:
    - plr
    useProtectionLimits: true
database:
    adapter: sqlite
    path: plugins/LWC/lwc.db
    host: localhost
    database: lwc
    username: ''
    password: ''
    prefix: lwc_
    ping_interval: 300
protections:
    denyRedstone: false
    denyHoppers: true
    autoRegister: false
    ignoreBlockDestruction: false
    ignoreLeftClick: false
    ignoreRightClick: false
    ignoreExplosions: false
    allowEntityBreakDoor: false
    allowEntityInteract: false
    quiet: false
    readonly-modify: false
    readonly-remove: false
    blocks:
        chest:
            enabled: true
            autoRegister: private
        furnace:
            enabled: true
            autoRegister: private
        dispenser:
            enabled: true
            autoRegister: private
        sign:
            enabled: true
        wooden_door:
            enabled: true
        iron_door:
            enabled: false
        spruce_door:
            enabled: true
        birch_door:
            enabled: true
        jungle_door:
            enabled: true
        acacia_door:
            enabled: true
        dark_oak_door:
            enabled: true
        trap_door:
            enabled: true
        iron_trapdoor:
            enabled: true
        fence_gate:
            enabled: true
        spruce_fence_gate:
            enabled: true
        birch_fence_gate:
            enabled: true
        jungle_fence_gate:
            enabled: true
        acacia_fence_gate:
            enabled: true
        dark_oak_fence_gate:
            enabled: true
        ARMOR_STAND:
            enabled: true
            autoRegister: private
        ITEM_FRAME:
            enabled: true
            autoRegister: private
        PAINTING:
            enabled: true
        LEASH_HITCH:
            enabled: false
        VILLAGER:
            enabled: false
        skull:
            autoRegister: private
            enabled: true
        dragon_egg:
            autoRegister: private
            enabled: true
        trapped_chest:
            autoRegister: private
            enabled: true
modes:
    droptransfer:
        enabled: true
        crossWorld: false
    persist:
        enabled: true
`

**Comment by pop4959** [comment] 2018-08-31 12:16
Ah, no problem. I'm here to help. Although the updates for 1.13 are taking priority right now, I can still take another look at your issue.

Just so you're aware, the latest development builds should be capable of migrating your database to a 1.13 server. The migration code was introduced about 2 days ago, and with an update today to fix some minor outstanding issues (which were mostly related to MySQL, not SQLite). Just be sure to backup your database before trying to migrate. I recommend trying it on a test server first and confirming that all protections are still working.

That being said, it would be helpful to know if you encounter the same issues on the latest development build, as you are in LWC 1.9.4.

Your set-up seems relatively similar to mine (SQLite with about 100,000 protections). The only difference is that I do not use entity locking. This could potentially be the issue, given that current implementation of entity locking is known to be extremely buggy. If this is the issue, we will probably not fix it, since all support for this plugin's entity locking features was solely provided by the previous maintainer. We are thinking about completely re-writing the entity locking features in the future, so it makes no sense to spend any time fixing the current implementation.

The config.yml you posted looks pretty normal except for the inclusion of several entities.

I'll take another look at this later today, and see if I can reproduce the problem. Keep in mind, it's not that I wouldn't care to try implementing a cancel command, but I still don't think it would be necessary. As you mentioned, the problem is that the command is hanging when you use it. I'd very much want to look into that problem first before implementing a workaround.

Think about it this way: If a cancel command were necessary, then the cleanup command would probably be so slow that you wouldn't even want to bother using it anyway. And if you didn't want to use the cleanup command, you wouldn't need a cancel command.

Feel free to add me on Discord (pop4959#1781) if you want to talk about this later one on one.

**Comment by pop4959** [comment] 2018-09-15 08:51
We talked about this on Discord, and came to the conclusion that this seems to be working as intended. Also, there are no plans to add a cancel option for the cleanup, but I might try to see if the cleanup can be made a bit more efficient.

**Closed by pop4959** 2018-09-15 08:51 UTC
Labels: wontfix
