### ISSUE TITLE
New option for global limit

### ISSUE THREAD

**Issue by JohOply** [Tsuser1/Modern-LWC#11] opened 2018-08-23 12:14 UTC
Hey guys

First, thank you to allow this plugin to continue to live.

I reported an issue here about global limit ("default" limit in limitsv2.yml) https://github.com/megoesrawr/Modern-LWC/issues/97, but it wasn't a bug.

So I think it could be interesting to add an option to choose behaviour of global limit
- current way: global limit is used only if any other limit is mentionned
- new behaviour: global limit is a maximum number of protections allowed per player

```
default_limit_behaviour: if_nothing_else
default_limit_behaviour: max_limit
```

I think it could be an interesting behaviour to add a maximum number of protections per player/group, but still allow them to choose the type of protections they want to use

Cheers

**Comment by pop4959** [comment] 2018-08-23 16:16
I'm not sure I understand your issue. I believe you can simply change "unlimited" to whatever number you want in limitsv2.yml to achieve this effect. There is also a groups, and players section where you can set limits per group or per player.

**Comment by Tsuser1** [comment] 2018-08-24 14:26
So to translate this to logic

`doorProtectionsOfPlayer <= globalDoorProtections`
`chestProtectionsOfPlayer <= globalChestProtections`
`globalChestProtections + globalDoorProtections <= globalProtectionLimit`

**Comment by JohOply** [comment] 2018-08-24 14:28
Yeah I think it is a good translation

**Comment by JohOply** [comment] 2018-08-24 14:33
I think the current behaviour is understandable but weird, because it takes into account per block protections limits for display it, but it is binding only if there is not any defined per block limit

**Comment by pop4959** [comment] 2018-08-24 15:28
@JohOply Would you mind sharing your configuration files (core and limitsv2)? Also, assuming you start with a fresh database, what would be the steps to reproduce this issue? If you could detail in words, or leave a video, explaining the exact steps to take to break the limits, it would help a lot. I have never needed to change LWC's limits in the 5+ years I've used it, so I do need a little hand holding here as I don't quite have experience with it.

PS: Sorry for mistakenly closing your issue on this in the other repository. We were trying to clean up fixed issues so that we can focus on ones that still need attention. It seems like this may in fact be a bug in LWC and not "working as intended" as implied by megoesrawr.

**Comment by pop4959** [comment] 2018-08-31 10:57
This should be fixed in the latest development build. The limits module seems to now correctly block every case where the player exceeds either the default limit, or some individual block limit.

Screenshots:
[https://imgur.com/a/D3zr8BK](https://imgur.com/a/D3zr8BK)

**Closed by pop4959** 2018-08-31 10:57 UTC
Labels: bug, good first issue

**Comment by JohOply** [comment] 2018-09-03 09:18
Sorry I did not available last days
Thank you for fixing, on your screens it seems work!
