### ISSUE TITLE
UUID fetching problem

### ISSUE THREAD

**Issue by roman901** [Tsuser1/Modern-LWC#59] opened 2018-10-31 19:04 UTC
Hi.

I have a server with custom authentication with authlib patches.

When player (maryzakat in this case) was added by /cmodify maryzakat UUID fetched from Mojang servers (there is MaryZakat account exists), by UUIDFetcher (https://github.com/Tsuser1/Modern-LWC/blob/master/src/main/java/com/griefcraft/util/UUIDRegistry.java#L128).
If player create protection by itself, all OK, UUID fetched by Bukkit's Player class (https://github.com/Tsuser1/Modern-LWC/blob/master/src/main/java/com/griefcraft/modules/create/CreateModule.java#L158)

**Comment by pop4959** [comment] 2018-10-31 20:23
@roman901 Please check and include all information asked for in the issue template. You haven't provided enough information for me to investigate this issue. Also, try to give a more detailed description of the issue you are having.

**Comment by roman901** [comment] 2018-10-31 20:30
@pop4959 oh, okay.
LWC Version (/lwc admin version):
2.1.1

Server version (/version):
1.13

Short five word summary of issue:
LWC don't support custom authlib & custom UUID source

Detailed description of problem:
I use https://github.com/new-sashok724/Launcher (**VERY** popular in Russian community). It provides custom authlib and UUID generation.
When player tries to /cmodify <player>, LWC took UUID from official Mojang servers, which is not equals to target player's UUID at this server, and target player don't get access to container.

**Comment by pop4959** [comment] 2018-10-31 20:57
Thanks for the specifics!

I take it that this is an offline mode server? I don't think LWC was designed with custom UUIDs in mind. They are supposed to be standard with Mojang's auth system, as far as I'm aware.

That being said, is this only an issue with cmodify or with the plugin in general? Also, when did this become an issue? When you upgraded to 1.13 or due to using your custom ID libraries?

What changes would you suggest to fix this? Consider making a pull request if you write code. This would probably be the quickest. If you don't, try to give me a detailed description of how to set up an environment for this issue, and what I'd need to do to replicate it. Then, at least, I could consider investigating it further.

**Comment by roman901** [comment] 2018-10-31 21:03
I don't think that it is a real bug.
In general, methods with uses Player.getUniqueId() works correctly (/cprivate, for example). Methods, which operates with player's nickname (and use UUIDRegistry) are "broken" in my case.

I try to find a solution, we must use _server's authlib_ rather making requests to Mojang. I wll try make PR to you.
Thank's for fast reply!

**Comment by pop4959** [comment] 2018-10-31 21:16
I haven't really looked at UUIDRegistry much, but I think it was added around the time that UUIDs were new to MineCraft. If Bukkit's built-in methods supercede it, perhaps it can be replaced.

**Comment by pop4959** [comment] 2018-11-19 02:04
@roman901 The issue might be fixed in the latest development build. Unfortunately, a repository for the project seems to have permanently shut down and we are in the process of setting up a replacement. As such, you cannot download this build currently from the build server, but if you want to try a copy of the build please message me on Discord.

**Comment by pop4959** [comment] 2018-11-25 23:07
Forgot to update this, but roman discussed this with me on Discord, and as he mentioned previously it is not a real bug, but more of a feature request because it involves adding extra support for non-standard authentication methods.

I will probably not work on this, but if @roman901 or anyone else wants this feature it remains open to PR.

**Comment by pop4959** [comment] 2019-07-05 19:09
I'm assuming this is no longer needed, so I am cleaning up the issue. Let me know if you were still planning to make some integration and I will try to accommodate it. But since this is not a popular/requested issue, I am going to close it now,.

**Closed by pop4959** 2019-07-05 19:09 UTC
Labels: enhancement
