### ISSUE TITLE
Drop Transfer will keep working after destroying the designated container

### ISSUE THREAD

**Issue by lifehome** [Tsuser1/Modern-LWC#80] opened 2018-12-31 13:18 UTC
**LWC Version (/lwc admin version):** 2.1.2-dev-4d34ea2
**Server version (/version):** Paper 1.13.2 git-Paper-488

**Short five word summary of issue:** It just doesn't make sense

**Detailed description of problem:**
To replicate:
1) Lock a container, a chest for example.
2) Use `/cdroptransfer select` to pick the chest
3) (Not needed) drop something to test the functionality (which it will work)
4) Destroy the chest
5) Continue drop something
6) You will find those item dropped at step 5 gone missing.

**Comment by pop4959** [comment] 2018-12-31 20:46
@lifehome Unable to reproduce this issue on 2.1.2-dev-4d34ea2 (I happen to be running the same version on my server haha) and Paper-486. Items go to chest, and when broken, drop normally.

**Comment by pop4959** [comment] 2019-01-02 21:44
Closing this issue now since it seems the feature is working as intended. Will re-open if someone can confirm this as a bug in the latest version of LWC and CraftBukkit/Paper, without any other plugin installed.

**Closed by pop4959** 2019-01-02 21:44 UTC
Labels: invalid
