### ISSUE TITLE
pistons can remove some protections

### ISSUE THREAD

**Issue by seema84** [Tsuser1/Modern-LWC#88] opened 2019-02-23 07:37 UTC
Version: 2.1.3-dev-e9744bb

pistons can move protected doors,trapdoors, fance gates (and maybe more)

**Comment by pop4959** [comment] 2019-02-23 09:50
Unable to replicate the issue. Do you have hopper protection disabled in the config? If not, please post it here via a hastebin.

**Comment by seema84** [comment] 2019-02-23 10:53
protections:
denyHoppers: false

**Comment by pop4959** [comment] 2019-02-23 22:35
Full config please. Use a service like pastebin. If you do not wish to share it publicly, please join the discord and send it to us in a private message.

**Comment by pop4959** [comment] 2019-02-27 00:28
Again unable to replicate the issue, using the config file sent via Discord (changing only the login credentials). Perhaps this is a plugin conflict. Have you tried testing whether this occurs on a clean server, with only LWC installed?

**Comment by seema84** [comment] 2019-02-27 08:26
Thats not a config issue. On a fresh Server with only Modern LWC (and a fresh config) its the same problem.

**Comment by pop4959** [comment] 2019-02-27 09:02
What kind of server are you running this on? Also, a video may help. No luck replicating this whatsoever. Can't fix something until the source of the problem is known.

**Comment by seema84** [comment] 2019-02-27 09:09
Paper version git-Paper-492 (MC: 1.13.2)

**Comment by pop4959** [comment] 2019-02-27 09:21
Ok finally confirmed (after discussing this with you on Discord). You left out some important details in this issue about how to cause this to occur. Now I see, but in the future please give a more thorough report. I will try to fix this soon.

**Comment by seema84** [comment] 2019-02-27 09:47
If you had tested all the possibilities (with pistons), you would have found it.

**Comment by pop4959** [comment] 2019-02-27 10:06
This should be fixed now in the latest development build.

In response to your last comment though, please actually make a proper report next time, by filling out the issue template. I spent a lot more time than I needed to because you did not describe the problem clearly. Many people report issues that are non-existent (caused by their server / other plugins), and if this were one of those cases I would not ever have found the bug regardless of the amount of testing. It is important that you give enough information. Please bear that in mind next time. Thanks!

Closing now

**Closed by pop4959** 2019-02-27 10:06 UTC
Labels: bug
