### ISSUE TITLE
MySQL Exceptions

### ISSUE THREAD

**Issue by Momshroom** [Tsuser1/Modern-LWC#102] opened 2019-05-03 08:07 UTC
**LWC Version (/lwc admin version):** 
2.1.3-87f48cb/

**Server version (/version):** 
Spigot 1.13.2, final build. 
This server is running CraftBukkit version git-Spigot-1a3504a-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Short five word summary of issue:** 
Occasional console error.

**Detailed description of problem:**
Console error periodically appears.  I'm very sorry but I don't know what causes it.

**If there was an error in console, put it here:**
```
https://pastebin.com/t1WhjRnj
```

**Comment by pop4959** [comment] 2019-05-03 08:58
Try disabling history in core.yml, if you are not using it.

**Comment by Momshroom** [comment] 2019-05-04 07:13
As it's an intermittent issue, I can't be sure, but it seems gone after disabling history. Ty.

**Comment by pop4959** [comment] 2019-05-04 10:42
Ah OK. I'll close this for now, but please re-open the issue if you still have it. I'm not too sure what the problem is, but I think one other person has had this issue and I think it was resolved after changing that config option. Thanks

**Closed by pop4959** 2019-05-04 10:42 UTC
Labels: question
